name = "fstring"
version = "1.0.0"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2024, Jason Christopherson"
description = "A modern Fortran string library."
homepage = "https://github.com/jchristopherson/fstring"

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "fstring_test"
source-dir = "test"
main = "fstring_test.f90"